export default {
    currentLang: "zh",
    text: {
        settings: {"zh": "设置", "ja": "設定", "en": "Settings"},
        darkMode: {"zh": "深色模式", "ja": "ダークモード", "en": "Dark Mode"},
        primaryColor: {"zh": "主色调", "ja": "プライマリカラー", "en": "Primary Color"},
        red: {"zh": "红色", "ja": "赤", "en": "Red"},
        yellow: {"zh": "黄色", "ja": "黄", "en": "Yellow"},
        green: {"zh": "绿色", "ja": "緑", "en": "Green"},
        blue: {"zh": "蓝色", "ja": "青", "en": "Blue"},
        language: {"zh": "语言", "ja": "言語", "en": "Language"},
        databaseList: {"zh": "数据库列表", "ja": "データベースリスト", "en": "Database List"},
        backToList: {"zh": "返回列表", "ja": "リストに戻る", "en": "Back to List"},
        plus: {"zh": "新建", "ja": "新規作成", "en": "New"},
        import: {"zh": "导入", "ja": "インポート", "en": "Import"},
        export: {"zh": "导出", "ja": "エクスポート", "en": "Export"},
        delete: {"zh": "删除", "ja": "削除", "en": "Delete"},
        edit: {"zh": "编辑", "ja": "編集", "en": "Edit"},
        search: {"zh": "搜索", "ja": "検索", "en": "Search"},
        gridView: {"zh": "网格视图", "ja": "グリッドビュー", "en": "Grid View"},
        listView: {"zh": "列表视图", "ja": "リストビュー", "en": "List View"},
        listShowItems: {"zh": "列表显示项", "ja": "リスト表示項目", "en": "List Show Items"},
        gridLarge: {"zh": "网格:大", "ja": "グリッド:大", "en": "Grid:Large"},
        gridDefault: {"zh": "网格:默认", "ja": "グリッド:デフォルト", "en": "Grid:Default"},
        gridSmall: {"zh": "网格:小", "ja": "グリッド:小", "en": "Grid:Small"},
        sortBy: {"zh": "排序方式", "ja": "ソート順", "en": "Sort By"},
        groupSortBy: {"zh": "分组依据", "ja": "グループ分け", "en": "Group Sort By"},
        noData: {"zh": "无数据", "ja": "データなし", "en": "No Data"}
    }
}